### ISSUE TITLE
Request to Update India Map for Accurate Representation

### ISSUE THREAD

**Issue by mihirsam** [undpindia/dicra#94]
I noticed that the current map of India used in the project is incorrect. As an advocate for accurate representation, I kindly request you to update it with the correct map. This will ensure compliance with legal and cultural considerations while promoting a positive image.

Thank you for your attention to this matter.

**Comment by ambarish-narayanan** [comment]
We utilize a third-party service for our basemap, and the map representation issue originates from their end. However, we've implemented a workaround to rectify the problem and ensure that the map now reflects the correct representation of India.
